<a href="https://colab.research.google.com/github/sandeepcoder097/Python/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [13]:
x=np.ones((3,3),dtype=np.uint8)
print(x)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [15]:
y=np.triu(x,k=0)
print(y)

[[1 1 1]
 [0 1 1]
 [0 0 1]]
